# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: prometheus-additional-scrape-config
#   namespace: monitoring
# data:
#   additional-scrape-configs.yaml: |
#     - job_name: 'local-target-app'
#       static_configs:
#       - targets: ['local-target-app-service.default.svc.cluster.local:8080']
#       metrics_path: '/metrics'
#       scrape_interval: 30s
