# prometheus:
#   url: http://monitoring-kube-prometheus-prometheus.monitoring.svc
#   port: 9090

# rules:
#   default: false
#   external:
#   - seriesQuery: 'flask_http_request_duration_seconds_avg{job="local-target-app-direct"}'
#     name:
#       matches: "flask_http_request_duration_seconds_avg"
#       as: "flask_http_request_duration_seconds_avg"
#     metricsQuery: 'avg(flask_http_request_duration_seconds_avg{job="local-target-app-direct"})'
