# apiVersion: v1
# kind: Service
# metadata:
#   name: local-target-app-service
#   labels:
#     app: local-target-app
#   annotations:
#     prometheus.io/scrape: "true"
#     prometheus.io/port: "8080"
#     prometheus.io/path: "/metrics"
# spec:
#   type: NodePort # Exposes the service on a static port on the host node
#   selector:
#     app: local-target-app
#   ports:
#     - protocol: TCP
#       port: 8080 # The port the service will be available on inside the cluster
#       targetPort: 8080 # The port the latency-app container is listening on
#       # nodePort: 30080 # Optional: You can specify a port, or K8s will choose one