# # apiVersion: autoscaling/v2
# # kind: HorizontalPodAutoscaler
# # metadata:
# #   name: local-target-app-hpa
# # spec:
# #   scaleTargetRef:
# #     apiVersion: apps/v1
# #     kind: Deployment
# #     name: local-target-app-deployment # Must match the name in your deployment.yaml
# #   minReplicas: 1
# #   maxReplicas: 10 # The maximum number of pods to scale up to
# #   # metrics:
# #   # - type: Resource
# #   #   resource:
# #   #     name: cpu
# #   #     target:
# #   #       type: Utilization
# #   #       averageUtilization: 50 # Target 50% CPU usage
# #   metrics:
# #   - type: Pods
# #     pods:
# #       metric:
# #         name: flask_http_request_duration_seconds_avg # The metric from our app
# #       target:
# #         type: AverageValue
# #         averageValue: 500m # Target 500 milliseconds

# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: local-target-app-hpa
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: local-target-app-deployment
#   minReplicas: 1
#   maxReplicas: 10
#   metrics:
#   - type: Pods #External
#     external:
#       metric:
#         name: flask_http_request_duration_seconds_avg
#         selector:
#           matchLabels:
#             app: local-target-app
#       target:
#         type: AverageValue
#         averageValue: "500m"

# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: local-target-app-hpa
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: local-target-app-deployment
#   minReplicas: 1
#   maxReplicas: 10
#   metrics:
#   - type: Pods
#     pods:
#       metric:
#         name: flask_http_request_duration_seconds_avg
#       target:
#         type: AverageValue
#         averageValue: "500m"

# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: local-target-app-hpa
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: local-target-app-deployment
#   minReplicas: 1
#   maxReplicas: 10
#   metrics:
#   - type: Object
#     object:
#       metric:
#         name: flask_http_request_duration_seconds_avg
#       describedObject:
#         apiVersion: v1
#         kind: Service
#         name: local-target-app-service
#       target:
#         type: Value
#         value: "500" # Target 500 milliseconds

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: local-target-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: local-target-app-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80